name: Daily Weather to CSV

on:
  schedule:
    - cron:  '0 7 * * *'   # kasdien 07:00 UTC
  workflow_dispatch:      # leidžia paleisti rankiniu būdu

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          # Įsitikinam, kad yra requirements.txt
          if [ ! -f requirements.txt ]; then
            echo "❌ requirements.txt nerastas! Patikrink jo vietą."
            exit 1
          fi
          pip install -r requirements.txt

      - name: Fetch weather and append to CSV
        run: python fetch_weather.py

      - name: Commit & push CSV
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add weather.csv
          git diff --cached --quiet || git commit -m "chore: add daily weather data"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
